import sys
with open('c:/Users/AnkushR/Downloads/Delta_BTC_Options_Bot/Delta_BTC_Options_Bot/templates/dashboard.html', 'r', encoding='utf-8') as f:
    lines = f.readlines()

start_idx = 560
end_idx = 931
tab_live_content = ''.join(lines[start_idx:end_idx])

new_content = tab_live_content.replace('id="tab-live"', 'id="tab-livemode"')
new_content = new_content.replace('<!-- TAB 1: LIVE TRADE -->', '<!-- TAB 1.5: LIVE MODE TRADE -->')
new_content = new_content.replace('PAPER MODE ACTIVE', 'LIVE MODE ACTIVE')
new_content = new_content.replace('No USDT balance required', 'Real USDT balance required')
new_content = new_content.replace('id="equity-val"', 'id="live-equity-val"')
new_content = new_content.replace('id="mode-val"', 'id="live-mode-val"')
new_content = new_content.replace('id="loss-hits-val"', 'id="live-loss-hits-val"')
new_content = new_content.replace('id="lot-multiplier-val"', 'id="live-lot-multiplier-val"')
new_content = new_content.replace('id="api-status-badge"', 'id="live-api-status-badge"')
new_content = new_content.replace('id="next-day-paused-container"', 'id="live-next-day-paused-container"')
new_content = new_content.replace('id="next-day-paused-banner"', 'id="live-next-day-paused-banner"')
new_content = new_content.replace('id="dvol-badge"', 'id="live-dvol-badge"')
new_content = new_content.replace('id="iv-badge"', 'id="live-iv-badge"')
new_content = new_content.replace('id="market-regime-badge"', 'id="live-market-regime-badge"')
new_content = new_content.replace('id="consecutive-losses-badge"', 'id="live-consecutive-losses-badge"')
new_content = new_content.replace('id="call-sym"', 'id="live-call-sym"')
new_content = new_content.replace('id="call-strike"', 'id="live-call-strike"')
new_content = new_content.replace('id="call-entry"', 'id="live-call-entry"')
new_content = new_content.replace('id="call-current"', 'id="live-call-current"')
new_content = new_content.replace('id="call-pnl-usd"', 'id="live-call-pnl-usd"')
new_content = new_content.replace('id="call-pnl-inr"', 'id="live-call-pnl-inr"')
new_content = new_content.replace('id="call-pnl-pct"', 'id="live-call-pnl-pct"')
new_content = new_content.replace('id="call-delta"', 'id="live-call-delta"')
new_content = new_content.replace('id="call-gamma"', 'id="live-call-gamma"')
new_content = new_content.replace('id="call-status"', 'id="live-call-status"')
new_content = new_content.replace('id="put-sym"', 'id="live-put-sym"')
new_content = new_content.replace('id="put-strike"', 'id="live-put-strike"')
new_content = new_content.replace('id="put-entry"', 'id="live-put-entry"')
new_content = new_content.replace('id="put-current"', 'id="live-put-current"')
new_content = new_content.replace('id="put-pnl-usd"', 'id="live-put-pnl-usd"')
new_content = new_content.replace('id="put-pnl-inr"', 'id="live-put-pnl-inr"')
new_content = new_content.replace('id="put-pnl-pct"', 'id="live-put-pnl-pct"')
new_content = new_content.replace('id="put-delta"', 'id="live-put-delta"')
new_content = new_content.replace('id="put-gamma"', 'id="live-put-gamma"')
new_content = new_content.replace('id="put-status"', 'id="live-put-status"')
new_content = new_content.replace('id="total-pnl"', 'id="live-total-pnl"')
new_content = new_content.replace('id="total-pnl-pct"', 'id="live-total-pnl-pct"')
new_content = new_content.replace('id="total-pnl-bar"', 'id="live-total-pnl-bar"')
new_content = new_content.replace('id="hedge-status-badge"', 'id="live-hedge-status-badge"')
new_content = new_content.replace('id="hedge-size"', 'id="live-hedge-size"')
new_content = new_content.replace('id="hedge-pnl"', 'id="live-hedge-pnl"')
new_content = new_content.replace('id="manual-lot-size"', 'id="live-manual-lot-size"')

new_content = new_content.replace('id="paper-mode-note"', 'id="live-mode-note"')
new_content = new_content.replace('rgba(56, 189, 248, 0.1)', 'rgba(239, 68, 68, 0.1)')
new_content = new_content.replace('rgba(56, 189, 248, 0.3)', 'rgba(239, 68, 68, 0.3)')
new_content = new_content.replace('#38bdf8', '#ef4444')

new_content = new_content.replace('/api/start', '/api/live/start')
new_content = new_content.replace('/api/stop', '/api/live/stop')
new_content = new_content.replace('/api/manual_order', '/api/live/manual_order')
new_content = new_content.replace('/api/emergency_close', '/api/live/emergency_close')
new_content = new_content.replace('/api/toggle_regime', '/api/live/toggle_regime')
new_content = new_content.replace('/api/toggle_hedge', '/api/live/toggle_hedge')
new_content = new_content.replace('saveLotSize()', 'saveLiveLotSize()')

new_content = new_content.replace('id="rules-monitor-content"', 'id="live-rules-monitor-content"')

new_content = new_content.replace('id="pnlChart"', 'id="livePnlChart"')
new_content = new_content.replace('id="pnl-legend"', 'id="live-pnl-legend"')
new_content = new_content.replace('#tab-live.active { display: flex !important; }', '#tab-livemode.active { display: flex !important; }')

lines.insert(end_idx, new_content)

with open('c:/Users/AnkushR/Downloads/Delta_BTC_Options_Bot/Delta_BTC_Options_Bot/templates/dashboard.html', 'w', encoding='utf-8') as f:
    f.writelines(lines)
print('Dashboard updated successfully')
