import logging
from typing import Dict, Any

from hedge.models.events import EventBus, ExecutionEvent
from hedge.models.tick import TickResult

logger = logging.getLogger(__name__)

class ValidationEngine:
    """
    Read-only observer of the entire ARES pipeline in Shadow mode.
    Subscribes to EventBus for execution events.
    Receives deterministic TickResults from the ShadowPipelineValidator.
    Feeds validated historical data into ShadowAnalytics and ShadowStore.
    """
    
    def __init__(self, event_bus: EventBus, store, analytics):
        self.event_bus = event_bus
        self.store = store
        self.analytics = analytics
        
        # Subscribe to all execution events from Simulator and Synchronizer
        self.event_bus.subscribe(ExecutionEvent, self._handle_execution_event)
        
    def _handle_execution_event(self, event: ExecutionEvent):
        """
        Processes an execution event (fill, cancel, submit) purely for validation logging.
        """
        # Store in SQLite
        self.store.log_execution_event(event)
        # Update rolling analytics
        self.analytics.on_execution_event(event)

    def observe_tick(self, tick_result: TickResult):
        """
        Processes an immutable TickResult generated by the production orchestrator.
        """
        # Validate data integrity
        if not tick_result:
            return
            
        # Write exact canonical record to SQLite
        self.store.log_tick_result(tick_result)
        
        # Update live rolling analytics (in-memory)
        self.analytics.on_tick_result(tick_result)
        
        # Log critical decisions for visibility
        if tick_result.hedge_decision and tick_result.hedge_decision.action.name != "HOLD":
            logger.info(
                f"[VALIDATOR] Action={tick_result.hedge_decision.action.name} "
                f"Reason='{tick_result.hedge_decision.reason}' "
                f"Score={tick_result.risk_result.overall_risk_score if tick_result.risk_result else 0.0}"
            )
